Building DAG of jobs...
Provided cores: 1
Rules claiming more threads will be scaled down.
Unlimited resources: walltime, mem
Job counts:
	count	jobs
	1	CreateSomaticPON
	1	GATK_index
	1	all
	1	bwa_index
	1	download_knowVar
	1	multiQC_pre
	1	popCommon
	7

rule GATK_index:
    input: refGenome/canFam3_chr.fa
    output: refGenome/gatkIndex/genome.fa, refGenome/gatkIndex/genome.fa.fai, refGenome/gatkIndex/genome.dict
    jobid: 2
    resources: walltime=3600, mem=8000000000

Error in rule GATK_index:
    jobid: 2
    output: refGenome/gatkIndex/genome.fa, refGenome/gatkIndex/genome.fa.fai, refGenome/gatkIndex/genome.dict

RuleException:
CalledProcessError in line 237 of /home/aparigi/dogCancer/snakemake_pipeline/Snakefile:
Command ' set -euo pipefail;  
        if [ ! -f refGenome/gatkIndex/genome.fa ];then ln -s ../canFam3_chr.fa refGenome/gatkIndex/genome.fa;fi
        module load SAMTools/1.5
        module load picardTools/1.89
        samtools faidx "refGenome/gatkIndex/genome.fa"
        java -Xmx4g -jar $PICARD/CreateSequenceDictionary.jar R= refGenome/canFam3_chr.fa O= refGenome/gatkIndex/genome.dict ' returned non-zero exit status 1.
  File "/home/aparigi/dogCancer/snakemake_pipeline/Snakefile", line 237, in __rule_GATK_index
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job GATK_index since they might be corrupted:
refGenome/gatkIndex/genome.fa
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2021-01-15T094557.138416.snakemake.log
